### ISSUE TITLE
[feature] add size and kind/file type to index

### ISSUE THREAD

**Issue by hbfs** [Ellerhold/fs2es-indexer#9] opened 2022-02-20 03:28 UTC
Spotlight search works through finder on samba for filename and directory name as well as path. 

Last modified also appears in spotlight search, however size and kind/type of file is shown as `-`.

If you can point me to format samba is expecting, submitting a PR for adding size and kind should be straight forward.

**Comment by MatthiasKuehneEllerhold** [comment] 2022-02-22 09:28
Im not sure what samba is expecting, we have to research that first. Is samba even capable to return this kind of information?

**Comment by MatthiasKuehneEllerhold** [comment] 2022-02-23 06:47
Thanks for the links for samba <=> es, I'll look into it and build something!


Regarding sqlite: This might be possible if you could bring samba to talk to a sqlite database instead of elasticsearch. Alas only gnome tracker and elasticsearch is supported atm.

Opening a sqlite file in two process (indexer and samba) might work if only one of them writes (indexer), but I didnt test that. A full blown mysql server would be preferable in any situation though (caching, ...).

But: what makes elasticsearch so great in this situation is that it analyses the documents you add and automatically builds up a search index for the string fields. That means that full text searches are blazingly fast. Whereby full text searches in sqlite are painfully slow, and even in mariadb / mysql without any extra logic around them.

And thats what makes the index so big. It doesnt just save the document "as is" (that would be more or less 3 GB as you've described them). It also saves data for the fulltext search, e. g. it splits the filename into "parts" and lets you search them. This index can now be used for the full text search from samba / Spotlight. Thats what makes elasticsearch uniquely suitable for the job.

At least thats my understanding of the situation. If anybody knows more or is of different opinion feel free to correct me.


Regarding cronjobs: you can do it like that if you want, but the "daemon" mode is much better suited for this. A cronjob is executed every X hours, regardless of the previous command is already completed or not. And with no regards as to when this was completed. E. g. if you index via cronjob every 6 hours and it only takes 1 hour to complete, itll wait 5 hours between runs. If for some reason the index takes up more than 6 hours (e. g. rebuild of a raid, heavy load because of ?!), you'll have two processes running at the same time. Now if the second process indexes a file EARLIER than the first process, then this document will be updated twice (first from the 2nd process and then from the 1st). At the end of the 2nd process this document will be deleted, because its too old.

The daemon is a process that runs all the time and waits between indexing runs according to your configuration, e. g. 1 hour. All these problem described above cant happen with it.

**Comment by MatthiasKuehneEllerhold** [comment] 2022-02-24 11:48
Ive added indexing the filesize to ES but the Finder still shows "--" for size.
Thats why added a local test command to test the search locally without fiddling with CURL or installing kibana. Im using the exact same queries as Samba does and the filesizes are correctly returned.

Ive looked through the source code and found https://gitlab.com/samba-team/samba/-/blob/master/source3/rpc_server/mdssvc/mdssvc_es.c#L798

It seems like samba only uses the `path.real` attribute from the es query results, so a filesize is never displayed... 

So it seems like we're out of luck there! Clicking on the found file shows the filesize correctly, so thats all I can offer atm. I'll try to ask the samba-team if my findings are correct and if they can do something about it.

**Comment by MatthiasKuehneEllerhold** [comment] 2022-02-24 12:19
Using the filesize as search parameter works though. So the gain is 50% :D (well unsure if any1 uses this...)

**Comment by MatthiasKuehneEllerhold** [comment] 2022-02-24 14:38
@slowfranklin just confirmed to me, that only the path.real field will be used for returning to spotlight. Anything else wont get queried.

If anybody wants to implement it in samba: they're welcome to do so. I've never really written C before, so thats not a project I'd like to do.

So the indexer now has two alternatives now:
1. remove filesize again from the indexing and the es index. This would reduce the indexing time and the disk space needed for elasticsearch. But you couldnt use the filesize as filter.
2. Keep the indexing of the filesize, this slows down the indexing process and increases the disk spaces used for elasticsearch, but you could use it in a filter.

I guess variant 3: make it configurable is the best, but way more work-intensive for me. Same goes for last-modified and any other field...

**Comment by hbfs** [comment] 2022-02-24 16:33
Before I upgraded to debian 11, on debian 10 I used samba and finder search worked on the same samba share. It was slow but showed the filesizes and last modified.. trying to figure out what I did (set it up years ago)

I'd say hold off for now, unless other folks speak up. 
In the meantime, filesize terminal and `find -size` works fast

**Comment by MatthiasKuehneEllerhold** [comment] 2022-02-25 06:02
So this sounds like client side searching was active? Spotlight will use the server side index if samba signals it has one...

**Comment by hbfs** [comment] 2022-02-26 00:36
After I updated to debian 11, finder search stopped working completely - there were no spotlight directives in my samba config.  This is what lead me to elasticsearch and this repo :)

Looks like the default behavior was changed: https://bbs.archlinux.org/viewtopic.php?id=255232 
Will do some more testing

**Comment by Zeitkind** [comment] 2022-02-28 14:48
On Debian 11 I was not able to get any Finder results, but tbh, I struggled the last few days with elasticsearch ("ES"), and had no time to investigate further.
samba announces server side search (mdutil -s /Volumes/TestShare), but I get no results. Also, ES has paths and filenames, but no index of the content. I tried
/usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-attachment
to enable pdf etc. indexing, but have no idea if one need to "enable" content indexing anyhow or if you also need to install or run tika etc. pp.
https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html
My TestShare is full of pdf's, txt's and other simple stuff (basically a local mirror of the old Apple Support Area and more), but I don't get any result, eg.:
curl -XGET -u elastic:password https://localhost:9200/index-testdata/_search?q=Apple
gives me filenames (eg. {"filename":"Apple Remote Desktop 2.2.txt","filesize":66} but no content of any file. I remember playing around with Gnome Tracker years ago. It was unstable and you needed a DE and I had big problems with dbus stuff, but at least I got some content. There's now a howto in the Samba-WIKI, but I don't really want to go this way again...

**Comment by MatthiasKuehneEllerhold** [comment] 2022-02-28 15:11
This indexer does *not* index any content whatsoever. Please use https://github.com/dadoonet/fscrawler if you need that. This indexer was written precisly because I didnt want that!

**Comment by MatthiasKuehneEllerhold** [comment] 2022-03-01 14:34
We've got archives with terabytes of data. We dont want any content index there because the index alone would be huge and take forever! Thats why I wrote this script.

**Comment by Zeitkind** [comment] 2022-03-01 17:33
At the moment, I look for a NAS-like VM solution (running on proxmox and ESX) for splitting a data graveyard with >40TB. Some stuff will remain, other and esp. ancient stuff will go to an even-deeper-graveyard. Companies are all data hoarders... Don't really need content indexing, because it would take ages to index several TB's of catalogues and magazines - and for no good reason anyway.
A second project will hold less than 200GB of data, but filled with .doc, .pdf and such. I do need content indexing there.

**Comment by MatthiasKuehneEllerhold** [comment] 2022-03-07 07:31
So .. use the right tool for the right scenario ;-)

Please close this issue if there isnt anything I can do right now.

**Closed** 2022-03-11 01:04 UTC
Labels: enhancement
