### ISSUE TITLE
/fs2es-indexer/bin/python3: can't find '__main__' module in '/fs2es-indexer/fs2es-indexer'

### ISSUE THREAD

**Issue by AllergicToGrass** [Ellerhold/fs2es-indexer#36] opened 2023-09-22 04:11 UTC
I keep getting stuck at this step:

```
# Use our new virtual env to run the indexer
/opt/fs2es-indexer/bin/python3 /opt/fs2es-indexer/fs2es-indexer
```

I get this error:

`/opt/fs2es-indexer/bin/python3: can't find '__main__' module in '/opt/fs2es-indexer/fs2es-indexer'`

steps to reproduce:

1. Install python dependencies (python3, python3-venv, python3-yaml)
2. create "fs2es-indexer" folder
3. git clone repo into "fs2es-indexer"
4. follow "Installation in a virtual env" instructions in README.md
5. Last step doesn't seem to work

I've tried these steps using the opt directory like in the instructions and I also tried it in my home directory just in case it was a permission issue I wasn't aware of (I edited the instructions accordingly). Same error in both scenarios

Ubuntu 22.04.3

**Comment by MatthiasKuehneEllerhold** [comment] 2024-11-19 10:48
Im sorry, I dont have any insight on why this is happening on your machine.
On my debian 12 machine running `python3 fs2es-indexer` works flawlessly...

**Comment by MatthiasKuehneEllerhold** [comment] 2024-11-19 10:48
Im closing this because I have no reproducer and therefor cant test fixes. 
If anyone can help with this (via insights or code) that would be helpful!

**Closed by MatthiasKuehneEllerhold** 2024-11-19 10:48 UTC
